---
- name: Patch Arch Linux and reboot if needed
  hosts: archlinux
  become: yes
  tasks:
    - name: Synchronize pacman package database and update all packages
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Check if reboot is required
      stat:
        path: /run/reboot-required
      register: reboot_required_file

    - name: Reboot the machine if needed
      reboot:
      when: reboot_required_file.stat.exists